apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-banyqjoe
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-banyqjoe:5e3ca3f975023b2a3895d26fa04fad333c8a168c@sha256:cdddd7473178fb51d7b67037a444f9f0ee7c5d93c5d8cd50928ce46ffad40887
          name: container-image
